In [2]:
import numpy as np

g = 0.5
Matrix = np.array([[2 - g, -g / 2, -g / 2, -g / 2, -g / 2,0],[-g/2,4-g,-g/2,-g/2,0,-g/2],[-g/2,-g/2,6-g,0,-g/2,-g/2],[-g/2,-g/2,0,6-g,-g/2,-g/2],[-g/2,0,-g/2,-g/2,8-g,-g/2],[0,-g/2,-g/2,-g/2,-g/2,10-g]])


In [3]:
Matrix

array([[ 1.5 , -0.25, -0.25, -0.25, -0.25,  0.  ],
       [-0.25,  3.5 , -0.25, -0.25,  0.  , -0.25],
       [-0.25, -0.25,  5.5 ,  0.  , -0.25, -0.25],
       [-0.25, -0.25,  0.  ,  5.5 , -0.25, -0.25],
       [-0.25,  0.  , -0.25, -0.25,  7.5 , -0.25],
       [ 0.  , -0.25, -0.25, -0.25, -0.25,  9.5 ]])

## Diagonalization of the full matrix (ex. 2)

In [17]:
for g in [-1,-0.5,0,0.5,1]:
    Matrix = np.array([[2 - g, -g / 2, -g / 2, -g / 2, -g / 2,0],[-g/2,4-g,-g/2,-g/2,0,-g/2],[-g/2,-g/2,6-g,0,-g/2,-g/2],[-g/2,-g/2,0,6-g,-g/2,-g/2],[-g/2,0,-g/2,-g/2,8-g,-g/2],[0,-g/2,-g/2,-g/2,-g/2,10-g]])
    eigenvalues, eigenvectors = np.linalg.eigh(Matrix)
    idx = eigenvalues.argsort()
    sorted_eigenvalues = eigenvalues[idx]
    
    print(f"\n--- g = {g} ---")
    print(f"Ground State Energy (E1): {sorted_eigenvalues[0]:.4f}")
    print(f"Sorted Eigenvalues (E1 to E6): {sorted_eigenvalues}")



--- g = -1 ---
Ground State Energy (E1): 2.7799
Sorted Eigenvalues (E1 to E6): [ 2.77987014  4.79105976  7.          7.          9.06461857 11.36445153]

--- g = -0.5 ---
Ground State Energy (E1): 2.4369
Sorted Eigenvalues (E1 to E6): [ 2.43688426  4.45056324  6.5         6.5         8.52932678 10.58322572]

--- g = 0 ---
Ground State Energy (E1): 2.0000
Sorted Eigenvalues (E1 to E6): [ 2.  4.  6.  6.  8. 10.]

--- g = 0.5 ---
Ground State Energy (E1): 1.4168
Sorted Eigenvalues (E1 to E6): [1.41677428 3.47067322 5.5        5.5        7.54943676 9.56311574]

--- g = 1 ---
Ground State Energy (E1): 0.6355
Sorted Eigenvalues (E1 to E6): [0.63554847 2.93538143 5.         5.         7.20894024 9.22012986]


### Only the lowest states and 2h2p excitations (ex.3)

In [6]:
np.array([[2 - g, -g / 2, -g / 2, -g / 2, -g / 2],[-g/2,4-g,-g/2,-g/2,0],[-g/2,-g/2,6-g,0,-g/2],[-g/2,-g/2,0,6-g,-g/2],[-g/2,0,-g/2,-g/2,8-g]])

array([[ 1. , -0.5, -0.5, -0.5, -0.5],
       [-0.5,  3. , -0.5, -0.5,  0. ],
       [-0.5, -0.5,  5. ,  0. , -0.5],
       [-0.5, -0.5,  0. ,  5. , -0.5],
       [-0.5,  0. , -0.5, -0.5,  7. ]])

In [16]:
for val in [-1,-0.5,0,0.5,1]:
    g = val
    Matrix = np.array([[2 - g, -g / 2, -g / 2, -g / 2, -g / 2],[-g/2,4-g,-g/2,-g/2,0],[-g/2,-g/2,6-g,0,-g/2],[-g/2,-g/2,0,6-g,-g/2],[-g/2,0,-g/2,-g/2,8-g]])
    eigenvalues, eigenvectors = np.linalg.eigh(Matrix)
    idx = eigenvalues.argsort()
    eigenvectors = eigenvectors[:,idx]
    sorted_eigenvalues = eigenvalues[idx]
    
    print(f"\n--- g = {g} ---")
    print(f"Ground State Energy (E1): {sorted_eigenvalues[0]:.4f}")
    print(f"Sorted Eigenvalues (E1 to E6): {sorted_eigenvalues}")
    print("eigenvector:")
    print(eigenvectors[:,0])


--- g = -1 ---
Ground State Energy (E1): 2.7853
Sorted Eigenvalues (E1 to E6): [2.7853145  4.80030641 7.         7.09292722 9.32145187]
eigenvector:
[ 0.97376278 -0.1808187  -0.08642483 -0.08642483 -0.06443714]

--- g = -0.5 ---
Ground State Energy (E1): 2.4374
Sorted Eigenvalues (E1 to E6): [2.4373655  4.4560503  6.5        6.52898209 8.57760212]
eigenvector:
[ 0.99080056 -0.10745778 -0.05210802 -0.05210802 -0.03655937]

--- g = 0 ---
Ground State Energy (E1): 2.0000
Sorted Eigenvalues (E1 to E6): [2. 4. 6. 6. 8.]
eigenvector:
[1. 0. 0. 0. 0.]

--- g = 0.5 ---
Ground State Energy (E1): 1.4176
Sorted Eigenvalues (E1 to E6): [1.41759645 3.48545632 5.5        5.52940512 7.56754211]
eigenvector:
[0.98454712 0.13534642 0.07141819 0.07141819 0.04633791]

--- g = 1 ---
Ground State Energy (E1): 0.6489
Sorted Eigenvalues (E1 to E6): [0.64890655 3.         5.         5.10219552 7.24889793]
eigenvector:
[0.93661065 0.26254746 0.14896828 0.14896828 0.09719171]


### Calculating the Energies with the correction 
$E \sim E + E^{(2)} + E^{(3)}$

In [ ]:
for g in [-1,-0.5,0,0.5,1]:
    E_0 = 2 - g 
    E_2 = - (g**2 / 4)*(2/(4 + g) + 1/(6 + g) + 1/(2 + g))
    E_3_1 = - (g**3 / 8)*( (1/(g+4) + 1/(g+6))**2 +(1/(g+2) + 1/(g+4))**2)
    E_3_2 = - (g**3 / 8)*( 1/(g+6)**2 + 1/(g+2)**2 + 2/(g+4)**2 + 2/((g+4)*(g+6)) + 2/((g+2)*(g+4)))
    print(f"\n--- g = {g} ---")
    print(f"Perturbation Theory E0: {E_0:.4f}")
    print(f"Perturbation Theory E2: {E_2:.4f}")
    print(f"Perturbation Theory E3: {E_3_1 + E_3_2:.4f}")
    print(f"Perturbation Theory E3 analysis: {E_3_1:.4f}")  
    print(f"Perturbation Theory E3 cross terms: {E_3_2:.4f}")
    print(f"Perturbation Theory E: {E_0 + E_2 + E_3_1 + E_3_2:.4f}")



--- g = -1 ---
Perturbation Theory E0: 3.0000
Perturbation Theory E2: -0.4667
Perturbation Theory E3: 0.5156
Perturbation Theory E3 analysis: 0.2578
Perturbation Theory E3 cross terms: 0.2578
Perturbation Theory E: 3.0489

--- g = -0.5 ---
Perturbation Theory E0: 2.5000
Perturbation Theory E2: -0.0887
Perturbation Theory E3: 0.0352
Perturbation Theory E3 analysis: 0.0176
Perturbation Theory E3 cross terms: 0.0176
Perturbation Theory E: 2.4464

--- g = 0 ---
Perturbation Theory E0: 2.0000
Perturbation Theory E2: -0.0000
Perturbation Theory E3: -0.0000
Perturbation Theory E3 analysis: -0.0000
Perturbation Theory E3 cross terms: -0.0000
Perturbation Theory E: 2.0000

--- g = 0.5 ---
Perturbation Theory E0: 1.5000
Perturbation Theory E2: -0.0624
Perturbation Theory E3: -0.0165
Perturbation Theory E3 analysis: -0.0083
Perturbation Theory E3 cross terms: -0.0083
Perturbation Theory E: 1.4211

--- g = 1 ---
Perturbation Theory E0: 1.0000
Perturbation Theory E2: -0.2190
Perturbation Theory E3

## Calculating the Second Order contribution Wave function

In [27]:
for g in [-1,-0.5,0,0.5,1]:
    phi31 = (g/2)/(4 + g)
    phi41 = (g/2)/(6 + g)
    phi32 = (g/2)/(2 + g)
    phi42 = (g/2)/(4 + g)
    print(f"\n--- g = {g} ---")
    print(f"The vectors components are:{[phi31,phi41,phi32,phi42]} for 3-1,4-1,3-2,4-2")


--- g = -1 ---
The vectors components are:[-0.16666666666666666, -0.1, -0.5, -0.16666666666666666] for 3-1,4-1,3-2,4-2

--- g = -0.5 ---
The vectors components are:[-0.07142857142857142, -0.045454545454545456, -0.16666666666666666, -0.07142857142857142] for 3-1,4-1,3-2,4-2

--- g = 0 ---
The vectors components are:[0.0, 0.0, 0.0, 0.0] for 3-1,4-1,3-2,4-2

--- g = 0.5 ---
The vectors components are:[0.05555555555555555, 0.038461538461538464, 0.1, 0.05555555555555555] for 3-1,4-1,3-2,4-2

--- g = 1 ---
The vectors components are:[0.1, 0.07142857142857142, 0.16666666666666666, 0.1] for 3-1,4-1,3-2,4-2


In [29]:
for g in [-1,-0.5,0,0.5,1]:
    phi31 = (g/2)/(4 + g)
    phi41 = (g/2)/(6 + g)
    phi32 = (g/2)/(2 + g)
    phi42 = (g/2)/(4 + g)
    norm = np.sqrt(1+ phi31**2 + phi41**2 + phi32**2 + phi42**2)
    print(f"\n--- g = {g} ---")
    print(f"Normalized vector components are:{[phi31/norm,phi41/norm,phi32/norm,phi42/norm,1/norm]} for 3-1,4-1,3-2,4-2,0")


--- g = -1 ---
Normalized vector components are:[np.float64(-0.14530954842977412), np.float64(-0.08718572905786448), np.float64(-0.43592864528932235), np.float64(-0.14530954842977412), np.float64(0.8718572905786447)] for 3-1,4-1,3-2,4-2,0

--- g = -0.5 ---
Normalized vector components are:[np.float64(-0.07003986138722532), np.float64(-0.04457082088277975), np.float64(-0.16342634323685906), np.float64(-0.07003986138722532), np.float64(0.9805580594211545)] for 3-1,4-1,3-2,4-2,0

--- g = 0 ---
Normalized vector components are:[np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0)] for 3-1,4-1,3-2,4-2,0

--- g = 0.5 ---
Normalized vector components are:[np.float64(0.05507161620415624), np.float64(0.03812650352595433), np.float64(0.09912890916748124), np.float64(0.05507161620415624), np.float64(0.9912890916748124)] for 3-1,4-1,3-2,4-2,0

--- g = 1 ---
Normalized vector components are:[np.float64(0.09745645266170513), np.float64(0.06961175190121795), np.float64

## Exercise 7...

In [39]:
for g in [-1,-0.5,0,0.5,1]:
    dictonary = {(1,3): g+4, (1,4): g+6, (2,3): g+2, (2,4): g+4}
    E_0 = 2 - g 
    E_2 = - (g**2 / 4)*(2/(4 + g) + 1/(6 + g) + 1/(2 + g))
    E_3_1 = - (g**3 / 8)*( (1/(g+4) + 1/(g+6))**2 +(1/(g+2) + 1/(g+4))**2)
    E_3_2 = - (g**3 / 8)*( 1/(g+6)**2 + 1/(g+2)**2 + 2/(g+4)**2 + 2/((g+4)*(g+6)) + 2/((g+2)*(g+4)))
    E_4 = 0
    for i in range(1,3):
        for j in range(1,3):
            for a in range(3,5):
                for b in range(3,5):
                    # diagram 5 contribution
                    E_4 += - 1/(dictonary[(j,b)] * dictonary[(j,a)] * dictonary[(i,a)])
                    # diagram 6 contribution
                    E_4 += -1/(dictonary[(i,a)] * dictonary[(i,b)]* dictonary[(j,b)])
                    # diagram 14 contribution
                    E_4 += -1/(dictonary[(i,a)] * dictonary[(i,b)] * dictonary[(i,j+2)])
                    # diagram 15 contribution
                    E_4 += -1/(dictonary[(i,a)] * dictonary[(j,a)] * dictonary[(b-2,a)])
                    # diagram 36 contribution
                    E_4 += -1/(dictonary[(i,a)] * dictonary[(i,b)] * (dictonary[(i,a)] + dictonary[(j,b)]))
                    # diagram 37 contribution
                    E_4 += -1/(dictonary[(i,a)] * dictonary[(j,a)] * (dictonary[(i,a)] + dictonary[(i,b)]))
    E_4 *= (g**4 / 16)
    print(f"\n--- g = {g} ---")
    print(f"Perturbation Theory E0: {E_0:.4f}")
    print(f"Perturbation Theory E2: {E_2:.4f}")
    print(f"Perturbation Theory E3: {E_3_1 + E_3_2:.4f}")
    print(f"Perturbation Theory E4: {E_4:.4f}")
    print(f"Perturbation Theory E: {E_0 + E_2 + E_3_1 + E_3_2 + E_4:.4f}") 


--- g = -1 ---
Perturbation Theory E0: 3.0000
Perturbation Theory E2: -0.4667
Perturbation Theory E3: 0.5156
Perturbation Theory E4: -0.7527
Perturbation Theory E: 2.2962

--- g = -0.5 ---
Perturbation Theory E0: 2.5000
Perturbation Theory E2: -0.0887
Perturbation Theory E3: 0.0352
Perturbation Theory E4: -0.0182
Perturbation Theory E: 2.4283

--- g = 0 ---
Perturbation Theory E0: 2.0000
Perturbation Theory E2: -0.0000
Perturbation Theory E3: -0.0000
Perturbation Theory E4: -0.0000
Perturbation Theory E: 2.0000

--- g = 0.5 ---
Perturbation Theory E0: 1.5000
Perturbation Theory E2: -0.0624
Perturbation Theory E3: -0.0165
Perturbation Theory E4: -0.0056
Perturbation Theory E: 1.4155

--- g = 1 ---
Perturbation Theory E0: 1.0000
Perturbation Theory E2: -0.2190
Perturbation Theory E3: -0.1005
Perturbation Theory E4: -0.0588
Perturbation Theory E: 0.6217
